services:
  - type: web
    name: ai-website-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://jeeveshatwork:RTntEvE5Gt4hHW2M@namastenode.kcy1y.mongodb.net/?retryWrites=true&w=majority&appName=NamasteNode"
      - key: PORT
        value: 5000
    autoDeploy: true
